-- Inserir categorias de regras para o módulo de pedidos
INSERT INTO public.business_rule_categories (id, module_id, name, description, order_index) VALUES
(gen_random_uuid(), (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1), '1. Regras de Criação de Pedidos', 'Configurações para origem, numeração e dados obrigatórios dos pedidos', 1),
(gen_random_uuid(), (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1), '2. Regras de Validação e Aprovação', 'Configurações para validações prévias, workflow e prazos de aprovação', 2),
(gen_random_uuid(), (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1), '3. Regras de Transmissão ao Fornecedor', 'Configurações para envio, formato e versionamento de pedidos', 3),
(gen_random_uuid(), (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1), '4. Regras do Portal do Fornecedor', 'Configurações de acesso, visualização e funcionalidades do portal', 4),
(gen_random_uuid(), (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1), '5. Regras de Confirmação de Pedidos', 'Configurações para processo, validação e status de confirmação', 5),
(gen_random_uuid(), (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1), '6. Regras de Avisos de Entrega', 'Configurações para criação, validação e notificações de entrega', 6),
(gen_random_uuid(), (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1), '7. Regras de Recebimento e Conferência', 'Configurações para processo, qualidade e devoluções', 7),
(gen_random_uuid(), (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1), '8. Regras de Comunicação e Colaboração', 'Configurações para mensagens, documentos e colaboração', 8),
(gen_random_uuid(), (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1), '9. Regras de Alterações de Pedidos', 'Configurações para solicitação, aprovação e impacto de alterações', 9),
(gen_random_uuid(), (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1), '10. Regras de Cancelamento', 'Configurações para processo, custos e reposição de cancelamentos', 10),
(gen_random_uuid(), (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1), '11. Regras de Performance e Monitoramento', 'Configurações para KPIs, performance e alertas', 11),
(gen_random_uuid(), (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1), '12. Regras de Relatórios e Analytics', 'Configurações para dashboards, relatórios e analytics', 12),
(gen_random_uuid(), (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1), '13. Regras de Integração', 'Configurações para ERP, externa e APIs', 13);

-- Inserir templates de regras para Criação de Pedidos
INSERT INTO public.business_rule_templates (category_id, rule_key, name, description, rule_type, default_value, impact_level, order_index, is_core, requires_approval) VALUES
((SELECT id FROM public.business_rule_categories WHERE name = '1. Regras de Criação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'auto_create_from_events', 'Criar pedidos automaticamente de eventos adjudicados', 'Permite a criação automática de pedidos a partir de eventos de compra adjudicados', 'boolean', 'false', 'medium', 1, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '1. Regras de Criação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'auto_create_from_quotes', 'Criar pedidos automaticamente de cotações diretas', 'Permite a criação automática de pedidos a partir de cotações aprovadas', 'boolean', 'false', 'medium', 2, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '1. Regras de Criação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'auto_create_from_requisitions', 'Criar pedidos automaticamente de requisições aprovadas', 'Permite a criação automática de pedidos a partir de requisições aprovadas', 'boolean', 'true', 'high', 3, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '1. Regras de Criação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'allow_manual_creation', 'Permitir criação manual de pedidos', 'Permite que usuários criem pedidos manualmente', 'boolean', 'true', 'medium', 4, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '1. Regras de Criação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'sequential_numbering', 'Aplicar numeração sequencial automática', 'Define se a numeração dos pedidos deve ser sequencial e automática', 'boolean', 'true', 'high', 10, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '1. Regras de Criação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'numbering_by_cost_center', 'Usar numeração por centro de custo', 'Incluir centro de custo na numeração dos pedidos', 'boolean', 'false', 'medium', 11, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '1. Regras de Criação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'supplier_required', 'Exigir fornecedor obrigatório', 'Define o fornecedor como campo obrigatório', 'boolean', 'true', 'high', 20, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '1. Regras de Criação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'delivery_date_required', 'Exigir data de entrega obrigatória', 'Define a data de entrega como campo obrigatório', 'boolean', 'true', 'high', 21, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '1. Regras de Criação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'delivery_location_required', 'Exigir local de entrega obrigatório', 'Define o local de entrega como campo obrigatório', 'boolean', 'true', 'high', 22, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '1. Regras de Criação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'cost_center_required', 'Exigir centro de custo obrigatório', 'Define o centro de custo como campo obrigatório', 'boolean', 'true', 'high', 23, true, false);

-- Inserir templates de regras para Validação e Aprovação
INSERT INTO public.business_rule_templates (category_id, rule_key, name, description, rule_type, default_value, impact_level, order_index, is_core, requires_approval) VALUES
((SELECT id FROM public.business_rule_categories WHERE name = '2. Regras de Validação e Aprovação' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'validate_active_supplier', 'Validar fornecedor ativo e qualificado', 'Verifica se o fornecedor está ativo e qualificado antes de criar o pedido', 'boolean', 'true', 'high', 1, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '2. Regras de Validação e Aprovação' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'validate_supplier_docs', 'Verificar documentação do fornecedor em dia', 'Valida se a documentação do fornecedor está atualizada', 'boolean', 'true', 'high', 2, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '2. Regras de Validação e Aprovação' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'validate_budget_balance', 'Validar saldo orçamentário disponível', 'Verifica se há saldo orçamentário suficiente para o pedido', 'boolean', 'true', 'high', 3, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '2. Regras de Validação e Aprovação' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'approval_by_value', 'Aplicar aprovação por valor do pedido', 'Define workflow de aprovação baseado no valor do pedido', 'boolean', 'true', 'high', 10, true, true),
((SELECT id FROM public.business_rule_categories WHERE name = '2. Regras de Validação e Aprovação' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'approval_by_category', 'Aplicar aprovação por categoria', 'Exige aprovação específica baseada na categoria do produto/serviço', 'boolean', 'false', 'medium', 11, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '2. Regras de Validação e Aprovação' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'approval_deadline_days', 'SLA de aprovação (dias)', 'Define prazo em dias para aprovação de pedidos', 'numeric', '3', 'medium', 20, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '2. Regras de Validação e Aprovação' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'auto_escalation', 'Escalar automaticamente após prazo', 'Escalação automática quando o prazo de aprovação é ultrapassado', 'boolean', 'true', 'medium', 21, false, false);

-- Inserir templates de regras para Transmissão ao Fornecedor
INSERT INTO public.business_rule_templates (category_id, rule_key, name, description, rule_type, default_value, impact_level, order_index, is_core, requires_approval) VALUES
((SELECT id FROM public.business_rule_categories WHERE name = '3. Regras de Transmissão ao Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'auto_send_after_approval', 'Enviar pedido automaticamente após aprovação', 'Transmite o pedido automaticamente para o fornecedor após todas as aprovações', 'boolean', 'true', 'high', 1, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '3. Regras de Transmissão ao Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'require_manual_send', 'Exigir envio manual do pedido', 'Requer intervenção manual para envio do pedido ao fornecedor', 'boolean', 'false', 'medium', 2, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '3. Regras de Transmissão ao Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'auto_email_send', 'Enviar por e-mail automaticamente', 'Envia o pedido por e-mail automaticamente', 'boolean', 'true', 'medium', 3, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '3. Regras de Transmissão ao Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'supplier_portal_available', 'Disponibilizar no portal do fornecedor', 'Disponibiliza o pedido no portal online do fornecedor', 'boolean', 'true', 'high', 4, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '3. Regras de Transmissão ao Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'require_receipt_confirmation', 'Exigir confirmação de recebimento', 'Requer confirmação do fornecedor sobre o recebimento do pedido', 'boolean', 'true', 'medium', 5, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '3. Regras de Transmissão ao Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'auto_generate_pdf', 'Gerar PDF automaticamente', 'Gera automaticamente PDF do pedido para envio', 'boolean', 'true', 'low', 10, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '3. Regras de Transmissão ao Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'maintain_versions', 'Manter versões do pedido', 'Controla versionamento das alterações do pedido', 'boolean', 'true', 'medium', 20, false, false);

-- Inserir templates de regras para Portal do Fornecedor
INSERT INTO public.business_rule_templates (category_id, rule_key, name, description, rule_type, default_value, impact_level, order_index, is_core, requires_approval) VALUES
((SELECT id FROM public.business_rule_categories WHERE name = '4. Regras do Portal do Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'single_login_per_supplier', 'Exigir login único por fornecedor', 'Permite apenas um login ativo por fornecedor', 'boolean', 'false', 'medium', 1, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '4. Regras do Portal do Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'multiple_users_per_supplier', 'Permitir múltiplos usuários por fornecedor', 'Permite múltiplos usuários ativos por fornecedor', 'boolean', 'true', 'medium', 2, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '4. Regras do Portal do Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'two_factor_auth', 'Aplicar autenticação de dois fatores', 'Exige autenticação de dois fatores para acesso ao portal', 'boolean', 'false', 'high', 3, false, true),
((SELECT id FROM public.business_rule_categories WHERE name = '4. Regras do Portal do Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'session_timeout_minutes', 'Timeout da sessão (minutos)', 'Define o tempo limite da sessão no portal em minutos', 'numeric', '60', 'low', 4, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '4. Regras do Portal do Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'show_all_open_orders', 'Mostrar todos os pedidos em aberto', 'Exibe todos os pedidos em aberto do fornecedor', 'boolean', 'true', 'medium', 10, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '4. Regras do Portal do Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'allow_order_confirmation', 'Permitir confirmação de pedidos', 'Permite que o fornecedor confirme pedidos através do portal', 'boolean', 'true', 'high', 20, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '4. Regras do Portal do Fornecedor' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'allow_delivery_notices', 'Permitir envio de avisos de entrega', 'Permite que o fornecedor envie avisos de entrega', 'boolean', 'true', 'high', 21, true, false);

-- Inserir templates de regras para Confirmação de Pedidos
INSERT INTO public.business_rule_templates (category_id, rule_key, name, description, rule_type, default_value, impact_level, order_index, is_core, requires_approval) VALUES
((SELECT id FROM public.business_rule_categories WHERE name = '5. Regras de Confirmação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'require_confirmation', 'Exigir confirmação obrigatória', 'Torna obrigatória a confirmação do pedido pelo fornecedor', 'boolean', 'true', 'high', 1, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '5. Regras de Confirmação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'confirmation_deadline_days', 'Prazo para confirmação (dias)', 'Define prazo em dias para confirmação do pedido', 'numeric', '3', 'medium', 2, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '5. Regras de Confirmação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'allow_partial_confirmation', 'Permitir confirmação parcial', 'Permite que o fornecedor confirme apenas parte do pedido', 'boolean', 'true', 'medium', 3, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '5. Regras de Confirmação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'allow_deadline_changes', 'Permitir alteração de prazos na confirmação', 'Permite que o fornecedor proponha novos prazos durante a confirmação', 'boolean', 'true', 'medium', 4, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '5. Regras de Confirmação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'validate_proposed_deadlines', 'Validar prazos propostos contra necessidade', 'Valida se os prazos propostos atendem à necessidade do solicitante', 'boolean', 'true', 'high', 10, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '5. Regras de Confirmação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'tolerance_percentage', 'Tolerância para alterações (%)', 'Define percentual de tolerância para alterações na confirmação', 'numeric', '5', 'medium', 11, false, false);

-- Inserir templates de regras para Avisos de Entrega
INSERT INTO public.business_rule_templates (category_id, rule_key, name, description, rule_type, default_value, impact_level, order_index, is_core, requires_approval) VALUES
((SELECT id FROM public.business_rule_categories WHERE name = '6. Regras de Avisos de Entrega' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'allow_delivery_notices', 'Permitir criação de avisos de entrega', 'Permite que fornecedores criem avisos de entrega', 'boolean', 'true', 'high', 1, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '6. Regras de Avisos de Entrega' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'require_confirmed_order', 'Exigir pedido confirmado para criar aviso', 'Requer que o pedido esteja confirmado antes de criar aviso de entrega', 'boolean', 'true', 'high', 2, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '6. Regras de Avisos de Entrega' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'allow_partial_deliveries', 'Permitir entregas parciais', 'Permite que o fornecedor faça entregas parciais do pedido', 'boolean', 'true', 'medium', 3, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '6. Regras de Avisos de Entrega' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'require_delivery_date', 'Exigir data de entrega no aviso', 'Torna obrigatória a informação da data de entrega', 'boolean', 'true', 'high', 4, true, false),
((SELECT id FROM public.business_rule_categories WHERE name = '6. Regras de Avisos de Entrega' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'notify_buyer_on_notice', 'Notificar comprador sobre avisos criados', 'Envia notificação para o comprador quando um aviso é criado', 'boolean', 'true', 'medium', 10, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '6. Regras de Avisos de Entrega' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'notify_receiver', 'Alertar recebedor sobre entregas', 'Notifica o responsável pelo recebimento sobre entregas programadas', 'boolean', 'true', 'medium', 11, false, false);

-- Inserir configurações globais
INSERT INTO public.business_rule_templates (category_id, rule_key, name, description, rule_type, default_value, impact_level, order_index, is_core, requires_approval) VALUES
((SELECT id FROM public.business_rule_categories WHERE name = '2. Regras de Validação e Aprovação' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'default_delivery_days', 'Prazo padrão para entrega (dias)', 'Define o prazo padrão em dias para entrega de pedidos', 'numeric', '15', 'medium', 30, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '5. Regras de Confirmação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'quantity_tolerance_days', 'Tolerância para prazo (dias)', 'Define tolerância em dias para atraso na entrega', 'numeric', '2', 'medium', 20, false, false),
((SELECT id FROM public.business_rule_categories WHERE name = '1. Regras de Criação de Pedidos' AND module_id = (SELECT id FROM public.modules WHERE type = 'pedidos' LIMIT 1)), 'minimum_order_value', 'Valor mínimo para pedido (R$)', 'Define o valor mínimo em reais para criação de pedidos', 'numeric', '100', 'low', 30, false, false);