// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lktdauwdmadjdnfbwnge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrdGRhdXdkbWFkamRuZmJ3bmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODM3MzUsImV4cCI6MjA2NTI1OTczNX0.JhBs7eSHYb6HiiVUvrCCSi3s2fUi-TLH_yg6Tvbio1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);